### ISSUE TITLE
tomcat reports port in use. Hydra fails to start.

### ISSUE THREAD

**Issue by bondesen** [linuxserver/docker-hydra2#13]
ubuntu 18.04

.__   __.  ________  .______   __    __  ____    ____  _______  .______          ___          ___

|  \ |  | |       /  |   _  \ |  |  |  | \   \  /   / |       \ |   _  \        /   \        |__ \

|   \|  | `---/  /   |  |_)  ||  |__|  |  \   \/   /  |  .--.  ||  |_)  |      /  ^  \          ) |

|  . `  |    /  /    |   _  < |   __   |   \_    _/   |  |  |  ||      /      /  /_\  \        / /

|  |\   |   /  /----.|  |_)  ||  |  |  |     |  |     |  '--'  ||  |\  \----./  _____  \      / /_

|__| \__|  /________||______/ |__|  |__|     |__|     |_______/ | _| `._____/__/     \__\    |____|

2018-10-21 11:59:27.192  INFO --- [           main] org.nzbhydra.NzbHydra                    : Starting NzbHydra on e0351b9ac1fa with PID 285 (/app/hydra2/lib/core-2.0.10-exec.jar started by abc in /app/hydra2)

2018-10-21 11:59:27.203  INFO --- [           main] org.nzbhydra.NzbHydra                    : The following profiles are active: default

WARNING: An illegal reflective access operation has occurred

WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/app/hydra2/lib/core-2.0.10-exec.jar!/BOOT-INF/lib/spring-core-5.0.8.RELEASE.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)

WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1

WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

WARNING: All illegal access operations will be denied in a future release

2018-10-21 11:59:30.454  INFO --- [           main] org.nzbhydra.config.BaseConfig           : Using data folder /config

2018-10-21 11:59:31.853  INFO --- [ost-startStop-1] o.n.a.HydraAnonymousAuthenticationFilter : Granting basic user rights to anonymous users

2018-10-21 11:59:31.855  INFO --- [ost-startStop-1] o.n.a.HydraAnonymousAuthenticationFilter : Granting stats rights to anonymous users

2018-10-21 11:59:31.855  INFO --- [ost-startStop-1] o.n.a.HydraAnonymousAuthenticationFilter : Granting admin rights to anonymous users

2018-10-21 11:59:32.252  WARN --- [           main] org.flywaydb.core.Flyway                 : Flyway.setCallbacks(FlywayCallback) has been deprecated and will be removed in Flyway 6.0. Use Flyway.setCallbacks(Callback) instead.

2018-10-21 11:59:32.327  INFO --- [           main] o.f.core.internal.util.VersionPrinter    : Flyway Community Edition 5.1.4 by Boxfuse

2018-10-21 11:59:32.333  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...

2018-10-21 11:59:32.948  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.

2018-10-21 11:59:32.956  INFO --- [           main] o.f.c.internal.database.DatabaseFactory  : Database: jdbc:h2:file:/config/database/nzbhydra (H2 1.4)

2018-10-21 11:59:33.251  INFO --- [           main] o.f.core.internal.command.DbValidate     : Successfully validated 15 migrations (execution time 00:00.179s)

2018-10-21 11:59:33.405  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Current version of schema "PUBLIC": 1.14

2018-10-21 11:59:33.410  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Schema "PUBLIC" is up to date. No migration necessary.

2018-10-21 11:59:36.464  WARN --- [           main] org.nzbhydra.NzbHydra                    : Overwritten settings will be displayed with their original value in the config section of the GUI

2018-10-21 11:59:37.823  INFO --- [           main] o.n.searching.SearchModuleProvider       : Loading indexers

2018-10-21 11:59:37.838  INFO --- [           main] o.n.searching.SearchModuleProvider       : Initializing indexer Binsearch

2018-10-21 11:59:37.911  INFO --- [           main] o.n.searching.SearchModuleProvider       : Initializing indexer NZB Finder

2018-10-21 11:59:37.932  INFO --- [           main] o.n.searching.SearchModuleProvider       : Initializing indexer NZBIndex

2018-10-21 11:59:37.934  INFO --- [           main] o.n.searching.SearchModuleProvider       : Initializing indexer Usenet-Crawler

2018-10-21 11:59:37.936  INFO --- [           main] o.n.searching.SearchModuleProvider       : Initializing indexer oznzb

2018-10-21 11:59:37.939  INFO --- [           main] o.n.searching.SearchModuleProvider       : Finished initializing active indexers

2018-10-21 11:59:37.974  INFO --- [           main] o.n.d.downloaders.DownloaderProvider     : Loading downloaders

2018-10-21 11:59:37.975  INFO --- [           main] o.n.d.downloaders.DownloaderProvider     : Initializing downloader SABnzbd

2018-10-21 11:59:38.063  INFO --- [           main] o.n.d.downloaders.DownloaderProvider     : Finished initializing active downloaders

2018-10-21 11:59:39.230  INFO --- [           main] org.nzbhydra.web.WebConfiguration        : Found folder /static. Will load UI resources from there

2018-10-21 11:59:41.274  INFO --- [           main] org.nzbhydra.tasks.HydraTaskScheduler    : Scheduling task "Delete short term storage results" to be run every 12 hours

2018-10-21 11:59:41.280  INFO --- [           main] org.nzbhydra.tasks.HydraTaskScheduler    : Scheduling task "Delete old history entries" to be run every 1 hour

2018-10-21 11:59:41.281  INFO --- [           main] org.nzbhydra.tasks.HydraTaskScheduler    : Scheduling task "Download queue check" to be run every 10 seconds

2018-10-21 11:59:41.282  INFO --- [           main] org.nzbhydra.tasks.HydraTaskScheduler    : Scheduling task "Backup" to be run every 1 hour

2018-10-21 11:59:41.283  INFO --- [           main] org.nzbhydra.tasks.HydraTaskScheduler    : Scheduling task "Clean up indexer statuses" to be run every 1 minute

2018-10-21 11:59:41.284  INFO --- [           main] org.nzbhydra.tasks.HydraTaskScheduler    : Scheduling task "Download history check" to be run every 10 minutes

2018-10-21 11:59:41.284  INFO --- [           main] org.nzbhydra.tasks.HydraTaskScheduler    : Scheduling task "Delete old search results" to be run every 1 hour

2018-10-21 11:59:41.343 ERROR --- [           main] o.apache.catalina.core.StandardService   : Failed to start connector [Connector[HTTP/1.1-5076]]

org.apache.catalina.LifecycleException: Failed to start component [Connector[HTTP/1.1-5076]]

	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)

	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:225)

	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:256)

	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:198)

	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:300)

	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162)

	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)

	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)

	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)

	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398)

	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)

	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:161)

	at org.nzbhydra.NzbHydra.main(NzbHydra.java:115)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

Caused by: org.apache.catalina.LifecycleException: Protocol handler start failed

	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1020)

	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)

	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:225)

	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:256)

	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:198)

	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:300)

	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162)

	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)

	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)

	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)

	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398)

	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)

	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:161)

	at org.nzbhydra.NzbHydra.main(NzbHydra.java:115)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

Caused by: java.net.BindException: Cannot assign requested address

	at java.base/sun.nio.ch.Net.bind0(Native Method)

	at java.base/sun.nio.ch.Net.bind(Net.java:433)

	at java.base/sun.nio.ch.Net.bind(Net.java:425)

	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:225)

	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)

	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:210)

	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1150)

	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:591)

	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1018)

	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)

	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:225)

	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:256)

	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:198)

	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:300)

	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162)

2018-10-21 11:59:41.382 ERROR --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************

APPLICATION FAILED TO START

***************************

Description:

The Tomcat connector configured to listen on port 5076 failed to start. The port may already be in use or the connector may be misconfigured.

Action:

Verify the connector's configuration, identify and stop any process that's listening on port 5076, or configure this application to listen on another port.

2018-10-21 11:59:41.393  INFO --- [           main] org.nzbhydra.NzbHydra                    : Shutting down

2018-10-21 11:59:41.400  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...

2018-10-21 11:59:41.621  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.

2018-10-21 11:59:41.624 ERROR --- [           main] org.nzbhydra.NzbHydra                    : The selected port is already in use. Either shut the other application down or select another port

2018-10-21 11:59:41,669  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it

Logging wrapper output to /config/logs/wrapper.log

2018-10-21 11:59:41,847  INFO - Determined java version as '10' from version string 'openjdk version "10.0.2" 2018-07-17'

2018-10-21 11:59:41,848  INFO - Starting NZBHydra main process with command line: java -Xmx512M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/config/logs -Xlog:gc*:file=../../config/logs/gclog-2018-10-21_11-59-41.log::filecount=10,filesize=5000 -Dspring.output.ansi.enabled=ALWAYS -jar /app/hydra2/lib/core-2.0.10-exec.jar --nobrowser --datafolder /config in folder /app/hydra2

**I also found this in the issue section of nzbhydra2's github:
https://github.com/theotherp/nzbhydra2/issues/219**
It's definately related. 

no

unfortunately not

**Comment by j0nnymoe** [comment]
Post your docker run command please

**Comment by bondesen** [comment]
Hi J0nnymoe, thank you for taking time to look into this. 
I deploy with ansible docker_container module. Here is it's configuration:

-docker_container:
       name: "hydra2"      
       image: "linuxserver/hydra2" 
       pull: yes 
       cpu_shares: 128 
       volumes
              - "/data/sysconfig/hydra2:/config"
              - "/etc/localtime:/etc/localtime:ro"
       env:
           PUID: "1234"      
           PGID: "1234"  
           TZ: "Europe/Copenhagen" 
       published_ports:
            - "5076:5076"      
       state: started
       restart_policy: always  
   tags: hydra2

**Comment by bondesen** [comment]
I found the reason. If anyone else has the same problem here is the cause:
In hydra2 configuration (set by web interface, saved in nzbhydra2.yml) if you, by mistake set "host" parameter to your docker host IP instead of 0.0.0.0 you will get the described error. Set it back to 0.0.0.0 and everything works like a charm.

**Comment by bondesen** [comment]
I found the reason. If anyone else has the same problem here is the cause:
In hydra2 configuration (set by web interface, saved in nzbhydra2.yml) if you, by mistake set "host" parameter to your docker host IP instead of 0.0.0.0 you will get the described error. Set it back to 0.0.0.0 and everything works like a charm.
