### ISSUE TITLE
constantly restarting 

### ISSUE THREAD

**Issue by Gerben-W** [linuxserver/docker-hydra2#32]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Current Behavior

Docker will have High CPU

## Steps to Reproduce

1.  Search from Radarr (linuxserver.io docker)
2.
3.
4.

## Environment
Docker on Unraid 6.8.2 installed via Apps

## Docker logs

2020-02-05 19:09:38,330  ERROR - Unable to start process; make sure Java is installed and callable. Error message: 'ascii' codec can't decode byte 0xc3 in position 309: ordinal not in range(128)
Logging wrapper output to /config/logs/wrapper.log
2020-02-05 19:09:38,551  INFO - Determined java version as '11' from version string 'openjdk version "11.0.6" 2020-01-14'
2020-02-05 19:09:38,551  INFO - Starting NZBHydra main process with command line: java -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/config/logs -Xlog:gc*:file=../../config/logs/gclog-2020-02-05_19-09-38.log::filecount=10,filesize=5000 -Dspring.output.ansi.enabled=ALWAYS -jar /app/hydra2/lib/core-2.13.2-exec.jar --nobrowser --datafolder /config in folder /app/hydra2
19:09:39.451 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/hydra2/lib/core-2.13.2-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep005to006.class]
19:09:39.452 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/hydra2/lib/core-2.13.2-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep008to009.class]
19:09:39.452 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Ignored because not a concrete top-level class: URL [jar:file:/app/hydra2/lib/core-2.13.2-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep.class]
19:09:39.609 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Writing to file /config/nzbhydra.yml
19:09:39.646 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.host to 0.0.0.0
19:09:39.646 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.urlBase to /
19:09:39.646 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseCompactTime to 15000
19:09:39.646 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.logfilelevel to INFO
19:09:39.722 [main] DEBUG org.nzbhydra.database.DatabaseRecreation - Determining if database recreation is needed
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-200]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
        at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:206)
        at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
        at org.h2.engine.Database.open(Database.java:675)
        at org.h2.engine.Database.<init>(Database.java:301)
        at org.h2.engine.Engine.openSession(Engine.java:192)
        at org.h2.engine.Engine.createSession(Engine.java:166)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at org.nzbhydra.database.DatabaseRecreation.runDatabaseScript(DatabaseRecreation.java:76)
        at org.nzbhydra.NzbHydra.main(NzbHydra.java:116)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
        at org.h2.engine.Database.getPageStore(Database.java:2659)
        at org.h2.engine.Database.openDatabase(Database.java:307)
        at org.h2.engine.Engine.openSession(Engine.java:74)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
        at org.h2.engine.Engine.createSession(Engine.java:29)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
        at org.h2.Driver.connect(Driver.java:69)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
        at org.nzbhydra.NzbHydra.startup(NzbHydra.java:162)
        ... 8 more
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
2020-02-05 19:09:39,859  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it
Logging wrapper output to /config/logs/wrapper.log
2020-02-05 19:09:39,999  INFO - Determined java version as '11' from version string 'openjdk version "11.0.6" 2020-01-14'
2020-02-05 19:09:39,999  INFO - Starting NZBHydra main process with command line: java -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/config/logs -Xlog:gc*:file=../../config/logs/gclog-2020-02-05_19-09-39.log::filecount=10,filesize=5000 -Dspring.output.ansi.enabled=ALWAYS -jar /app/hydra2/lib/core-2.13.2-exec.jar --nobrowser --datafolder /config in folder /app/hydra2
19:09:40.911 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/hydra2/lib/core-2.13.2-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep005to006.class]
19:09:40.912 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/hydra2/lib/core-2.13.2-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep008to009.class]
19:09:40.913 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Ignored because not a concrete top-level class: URL [jar:file:/app/hydra2/lib/core-2.13.2-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep.class]
19:09:41.046 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Writing to file /config/nzbhydra.yml
19:09:41.083 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.host to 0.0.0.0
19:09:41.083 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.urlBase to /
19:09:41.083 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseCompactTime to 15000
19:09:41.083 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.logfilelevel to INFO
19:09:41.164 [main] DEBUG org.nzbhydra.database.DatabaseRecreation - Determining if database recreation is needed

**Comment by nemchik** [comment]
I am not seeing this issue on my system. Have you checked with the dev of Hydra2 to see if this is abnormal? The application may need those resources during searches.

**Comment by j0nnymoe** [comment]
Likely a corrupted database.

**Comment by j0nnymoe** [comment]
no reply, closing.
