### ISSUE TITLE
Tomcat issue

### ISSUE THREAD

**Issue by splifter** [linuxserver/docker-hydra2#33]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Expected Behavior
Container should boot and make hydra2 available

## Current Behavior
doesn'start.

## Steps to Reproduce
Container was updated a couple a days ago via watchtower. After that the container didn't boot up again. Tried to re-create the container via Portainer, still not starting.

## Environment
**OS:**      Debian
**CPU architecture:** x86_64
**How docker service was installed:**      apt-get install...
Docker-CE installed, containers are managed by portainer and watchtower keeps containers up-to-date.

## Docker logs
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 01-envfile: executing... ,
[cont-init.d] 01-envfile: exited 0.,
[cont-init.d] 10-adduser: executing... ,
usermod: no changes,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
We gratefully accept donations at:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    911,
User gid:    911,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: executing... ,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] 99-custom-scripts: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-scripts: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
Logging wrapper output to /config/logs/wrapper.log,
2020-02-09 12:28:38,902  INFO - Determined java version as '11' from version string 'openjdk version "11.0.6" 2020-01-14',
2020-02-09 12:28:38,917  INFO - Starting NZBHydra main process with command line: java -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/config/logs -Xlog:gc*:file=../../config/logs/gclog-2020-02-09_12-28-38.log::filecount=10,filesize=5000 -Dspring.output.ansi.enabled=ALWAYS -jar /app/hydra2/lib/core-2.13.4-exec.jar --nobrowser --datafolder /config in folder /app/hydra2,
12:28:39.731 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/hydra2/lib/core-2.13.4-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep006to007.class],
12:28:39.732 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/hydra2/lib/core-2.13.4-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep004to005.class],
12:28:39.732 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/hydra2/lib/core-2.13.4-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep003to004.class],
12:28:39.873 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Writing to file /config/nzbhydra.yml,
12:28:40.037 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.host to 0.0.0.0,
12:28:40.037 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.urlBase to /,
12:28:40.038 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseCompactTime to 15000,
12:28:40.038 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.logfilelevel to INFO,
12:28:40.108 [main] DEBUG org.nzbhydra.database.DatabaseRecreation - Determining if database recreation is needed,
.__   __.  ________  .______   __    __  ____    ____  _______  .______          ___          ___
,
|   \|  | `---/  /   |  |_)  ||  |__|  |  \   \/   /  |  .--.  ||  |_)  |      /  ^  \          ) |
,
|  |\   |   /  /----.|  |_)  ||  |  |  |     |  |     |  '--'  ||  |\  \----./  _____  \      / /_
,
,
2020-02-09 12:28:41.008  INFO --- [           main] org.nzbhydra.NzbHydra                    : The following profiles are active: default,
2020-02-09 12:28:43.015  WARN --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.IllegalStateException: Unable to create the directory [/tmp/tomcat.14057262406604805254.5076] to use as the base directory,
,
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:156),
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141),
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397),
	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:164),
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48),
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51),
	at org.apache.catalina.startup.Tomcat.initBaseDir(Tomcat.java:819),
	at org.apache.catalina.startup.Tomcat.getService(Tomcat.java:561),
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:180),
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544),
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747),
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315),
	at org.nzbhydra.NzbHydra.main(NzbHydra.java:116),
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),
2020-02-09 12:28:43.039 ERROR --- [           main] org.nzbhydra.NzbHydra                    : An unexpected error occurred during startup,
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.IllegalStateException: Unable to create the directory [/tmp/tomcat.14057262406604805254.5076] to use as the base directory,
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544),
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747),
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315),
	at org.nzbhydra.NzbHydra.main(NzbHydra.java:116),
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),
	at java.base/java.lang.reflect.Method.invoke(Method.java:566),
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87),
Caused by: java.lang.IllegalStateException: Unable to create the directory [/tmp/tomcat.14057262406604805254.5076] to use as the base directory,
	at org.apache.catalina.startup.Tomcat.getServer(Tomcat.java:628),
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:182),
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:153),
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141),
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397),
	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:164),
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
,

**Comment by CHBMB** [comment]
Tried rolling back to a previous tag?  

https://github.com/linuxserver/docker-hydra2/releases

I'm running `latest` and not seeing this.

**Comment by splifter** [comment]
My mistake. Harddrive was full....
